#!/bin/sh
gofmt -w ./pkg/**/*.go
goimports -local github.com/wenerme/uo -w .

golangci-lint -E bodyclose,misspell,gocyclo,dupl,gofmt,golint,unconvert,goimports,depguard,gocritic,funlen,interfacer run --fix
